### ISSUE TITLE
pathPrefix

### ISSUE THREAD

**Issue by heathweaver** [greglobinski/gatsby-styled-blog-starter#11]
I know this project is closed in favour of a new gatsby theme, but I wanted to use the old version. I'm running into an issue where changing the pathPrefix is not being taken. 

I wanted to put in a blog folder and it keeps referring back to the root. I've tried changing the pathPrefix to both /blog and /blog/. 

Is this something core to Gatsby or perhaps the SEO component interfering? Any help is appreciated.

**Comment by heathweaver** [comment]
[Reading the manual](https://www.gatsbyjs.org/docs/path-prefix/) and I tried building with --prefix-paths option, but this still doesn't work. I can see that gatsby-link is installed and <Link to= is called, but then the pathPrefix is not used, rather just a reference to /

I am still trying to sort out how the URLs for the pages are generated as it looks like gatsby-link isn't used there.

**Comment by greglobinski** [comment]
Hi @heathweaver 
I'm sorry that I answer only now. As you mentioned, the project is closed, so I have not been watching it.

Did you resolve your problem? There should not be any.

I've just deployed the starter to Github pages https://greglobinski.github.io/gatsby-styled-blog-starter/
As you can see it works with pathPrefix `gatsby-styled-blog-starter`

Details are here https://www.gatsbyjs.org/docs/deploy-gatsby/#github-pages

I hope you already figured it out or the link will help you.

**Comment by heathweaver** [comment]
@greglobinski yes, actually it was pretty simple in the end to solve. I had to add the pathPrefix: "/" variable to the top of the gatsby-config. I am not sure why the include doesn't work properly. After doing that it worked perfectly without any other issues.
