### ISSUE TITLE
PNG images not showing up

### ISSUE THREAD

**Issue by jampy** [greglobinski/gatsby-styled-blog-starter#4]
For some reason I don't understand, the Blog does only display .jpg images within the Markdown content.

Whenever I add a `.png` image to an article, it silently gets ignored.

Any idea?

**Comment by jampy** [comment]
Seems to be an issue with PNG images generated by [a WebStorm plugin](https://plugins.jetbrains.com/plugin/8446-paste-images-into-markdown), that work fine elsewhere. 

Example of an image that doesn't display in `gatsby-styled-blog-starter`:

![8617a7f4](https://user-images.githubusercontent.com/820758/33893097-e5a70c34-df5a-11e7-8f5e-40e057626770.png)

**Comment by greglobinski** [comment]
I can't recreate the bug. The png file you posted works as it should, I've put it into the demo post 
https://gsbs.greglobinski.com/like-nonsense/ 

![fireshot capture 49 - i like nonsense it wakes up t_ - https___gsbs greglobinski com_like-nonsense_](https://user-images.githubusercontent.com/32480082/33905366-b0812c6e-df7e-11e7-91d7-6e9fffd1cf59.png)

Regrettably, I have no idea, what the plugin does with the png files. I suggest to place the picture code into the markdown file by hand to test if it helps.
